### ISSUE TITLE
Changes to embedded links for site

### ISSUE THREAD

**Issue by liamstar97** [Negative-Carbon-Reforestation-Project/openlayers-springboot-react-demo#38]
- modify embed text to: "Explore reforestation opportunities using our innovative toolkit."
- add NCRP logo to embed.

![image](https://user-images.githubusercontent.com/6600480/163737909-415d16e8-4942-48c7-a640-6e3c2ed8fc07.png)

**Comment by asathkumara** [comment]
Social media tags were added in the following commits
a6db1170dfbf73379c22195d2c111464b0a1d5d8
4ddbfa9fac0ea77b4ef2bf2da92171a5790b23d5


![image](https://user-images.githubusercontent.com/28933557/163851191-00862bce-7a5a-4f11-8f00-e96ec87a3409.png)
