### ISSUE TITLE
Fire history Layer not rendering

### ISSUE THREAD

**Issue by liamstar97** [Negative-Carbon-Reforestation-Project/openlayers-springboot-react-demo#39]
issues with rendering fire history on site

**Comment by asathkumara** [comment]
Log for future reference

![image](https://user-images.githubusercontent.com/28933557/163852833-15adc042-8cb7-46f5-932d-dd483701be0d.png)

https://geo.ncrp.app/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ncrp%3Awa_fire_history_low_dpi&TILED=true&WIDTH=320&HEIGHT=320&CRS=EPSG%3A3857&STYLES=&FORMAT_OPTIONS=dpi%3A113&BBOX=-13619243.951739565%2C5948635.289265556%2C-13462700.917811524%2C6105178.323193598

https://chromestatus.com/feature/5629709824032768

**Comment by asathkumara** [comment]
#43 opened to address this
