### ISSUE TITLE
Bug: query tool not working on mobile

### ISSUE THREAD

**Issue by Ameb8** [Negative-Carbon-Reforestation-Project/openlayers-springboot-react-demo#40]
Could not complete query to view reforestation probabilities when accessing the app through discord link. Happened on Samsung Galaxy S22

**Comment by liamstar97** [comment]
To add to this; the query pop up does not come up when a location is tapped after tool selection.

**Comment by asathkumara** [comment]
@Ameb8 Can you please list the steps to reproduce the error and is it only due to the discord embedded browser or does it work on a normal browser?

@liamstar97 Is this also an issue on the Samsung Galaxy S22?

**Comment by asathkumara** [comment]
Will be resolved in the upcoming prototype
